# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/processing/processing.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing || ORIG_REF_NAME==processing} -quiet] -quiet

# IP: bd/processing/ip/processing_processing_system7_0_0/processing_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_processing_system7_0_0 || ORIG_REF_NAME==processing_processing_system7_0_0} -quiet] -quiet

# IP: bd/processing/ip/processing_KetchupPeripheral_0_0/processing_KetchupPeripheral_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_KetchupPeripheral_0_0 || ORIG_REF_NAME==processing_KetchupPeripheral_0_0} -quiet] -quiet

# IP: bd/processing/ip/processing_ps7_0_axi_periph_0/processing_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_ps7_0_axi_periph_0 || ORIG_REF_NAME==processing_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/processing/ip/processing_rst_ps7_0_100M_0/processing_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_rst_ps7_0_100M_0 || ORIG_REF_NAME==processing_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/processing/ip/processing_auto_pc_0/processing_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processing_auto_pc_0 || ORIG_REF_NAME==processing_auto_pc_0} -quiet] -quiet

# XDC: /home/daem/Desktop/group9/KeccakHardware/VivadoProject/KetchupPlatform/KetchupPlatform.gen/sources_1/bd/processing/processing_ooc.xdc
